ALTER TABLE public.addresses
ADD COLUMN IF NOT EXISTS building TEXT,
ADD COLUMN IF NOT EXISTS area TEXT,
ADD COLUMN IF NOT EXISTS landmark TEXT;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS country_code TEXT,
ADD COLUMN IF NOT EXISTS delivery_slot TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
